name: NovaGamesLib-Bukkit
version: 0.0.4
description: An advanced API and library Bukkit minigames.
author: Shades161 (NovaFox161)
website: http://www.cloudcraftgaming.com

softdepend: [Vault, PerWorldChatPlus]

main: com.cloudcraftgaming.novagameslib.NovaGamesLib