name: NovaGamesLib
version: 1.0.0
description: An advanced API and library for Nova(Shades161)'s minigames.
author: Shades161
website: http://www.cloudcraftgaming.com

main: com.cloudcraftgaming.novagameslib.NovaGamesLib